### ISSUE TITLE
Show yellow emoji?

### ISSUE THREAD

**Issue by orschiro** [artf/EmojiBelt#1]
Dear @artf,

Really like your extension, thank you! 😄

I noticed that your emoji are black and white which makes them hard to search for. 

Could you use the same as Github uses?

![image](https://user-images.githubusercontent.com/170947/34460158-67e9b1aa-ee07-11e7-82a5-716ce3e6ae1d.png)

![image](https://user-images.githubusercontent.com/170947/34460165-847c58cc-ee07-11e7-8b49-7e9559052060.png)

**Comment by artf** [comment]
Hi Robert, the extension uses your default OS font (emojis are just Unicodes), so... 
it's Windowz ¯\_(ツ)_/¯

**Comment by orschiro** [comment]
I understand, thanks!
